#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2016 World Wide Technology, Inc. 
#      All rights reserved. 
#
#      author: Joel W. King, Mark Wall,  World Wide Technology
#      short_description: Automation of F5 LTM & GTM 
#      description: Importing configuration via CSV files to automat the deployment of applications for F5 LTM and GTM.
#                   This playbook will read a CSV file and create the LTM nodes, pools, vips, GTM pools and wide ips.
#
- name: icontrol F5 modules to automate WideIP
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    spark_room: F5


  tasks:
  - name: Decrypt the password file
    include_vars: "./passwords.yml"
    
  - name: Get facts from CSV file
    csv_to_facts:
      src: ./files/f5_wide_IP_gen_3.csv

  - name: Create LTM Nodes
    icontrol_install_config:
      uri: "/mgmt/tm/ltm/node"
      body: '{"name":"{{item.name}}","address":"{{item.address}}"}'
      host: "{{lookup('dig', item.appliance)}}"
      username: admin
      password: "{{password}}"
    with_items: "{{spreadsheet}}"
    when: item.selector_task == "NODE"

  - name: Create LTM Pool
    icontrol_install_config:
      uri: "/mgmt/tm/ltm/pool/"
      body: '{"name":"{{item.name}}","monitor":"/Common/http"}'
      host: "{{lookup('dig', item.appliance)}}"
      username: admin
      password: "{{password}}"
    with_items: "{{spreadsheet}}"
    when: item.selector_task == "LTM_POOL"

  - name: Add Nodes to LTM Pool
    icontrol_install_config:
      method: "_post_"
      uri: "/mgmt/tm/ltm/pool/{{item.pool}}/members"
      body: '{"name":"{{item.name}}:{{item.port}}"}'
      host: "{{lookup('dig', item.appliance)}}"
      username: admin
      password: "{{password}}"
    with_items: "{{spreadsheet}}"
    when: item.selector_task == "LTM_POOL_MEMBERS"

  - name: Create LTM VIP
    icontrol_install_config:
      uri: "/mgmt/tm/ltm/virtual"
      body: '{"name":"{{item.name}}", "destination":"/Common/{{item.address}}:{{item.port}}",  "ipProtocol":"tcp", "mask":"255.255.255.255", "pool":"/Common/{{item.pool}}", "sourceAddressTranslation":{"type":"automap"}}'
      host: "{{lookup('dig', item.appliance)}}"
      username: admin
      password: "{{password}}"
    with_items: "{{spreadsheet}}"
    when: item.selector_task == "LTM_VIP"

  - name: Wait for VIP Discovery
    wait_for:
      timeout: 5

  - name: Create GTM POOL
    icontrol_install_config:
      uri: "/mgmt/tm/gtm/pool/"
      body: '{"name":"{{item.name}}"}'
      host: "{{lookup('dig', item.appliance)}}"
      username: admin
      password: "{{password}}"
    with_items: "{{spreadsheet}}"
    when: item.selector_task == "GTM_POOL"

  - name: Create GTM POOL MEMBERS
    icontrol_install_config:
      uri: "/mgmt/tm/gtm/pool/{{item.pool}}/members"
      body: '{"name":"{{item.gtm_server}}:/Common/{{item.name}}"}'
      host: "{{lookup('dig', item.appliance)}}"
      username: admin
      password: "{{password}}"
    with_items: "{{spreadsheet}}"
    when: item.selector_task == "GTM_POOL_MEMBERS"

  - name: Create GTM WIDE IP
    icontrol_install_config: 
      uri: "/mgmt/tm/gtm/wideip"
      body: '{"name":"{{item.name}}", "pools":[{"name":"{{item.pool}}","partition":"Common","order":0,"ratio":1}]}'
      host: "{{lookup('dig', item.appliance)}}"
      username: admin
      password: "{{password}}"
    with_items: "{{spreadsheet}}"
    when: item.selector_task == "GTM_WIDEIP"
    
#  - name: Send message to spark room when successful
#    spark_room:
#      text: "F5 Wide IP Playbook has run succesfully "
#      room: "{{spark_room}}"
#      token: "{{spark_token}}"
